# Generated by Django 5.0 on 2024-02-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='comment',
            new_name='comments',
        ),
    ]
